#!/bin/bash
pkgname=cartesi-machine-emulator
pkgver=0.21.0
pkgrel=1
_pkgver=${pkgver}
sources=("${pkgname}_${pkgver}.orig.tar.gz::https://github.com/cartesi/machine-emulator/archive/refs/tags/v${_pkgver}.tar.gz"
         "debian/patches/add-generated-files.diff::https://github.com/cartesi/machine-emulator/releases/download/v${_pkgver}/add-generated-files.diff")
sha256sums=("44fc83cb08a1907e66ab225ccf421b0fdad3f145be35b9a9ffe561d3563e3eda  ${pkgname}_${pkgver}.orig.tar.gz"
            "596c5e171cac2e784aef01a26d47d19964b8593f74e37e863e0fcc1c9446be23  debian/patches/add-generated-files.diff")
arch=any

prepare() {
    tar -xf ${pkgname}_${pkgver}.orig.tar.gz
    mv machine-emulator-${_pkgver} ${pkgname}-${pkgver}
    patch -d ${pkgname}-${pkgver} -Np1 < debian/patches/add-generated-files.diff
}
