#!/bin/bash
pkgname=cartesi-machine-emulator
pkgver=0.19.0
pkgrel=1
_pkgver=${pkgver}
sources=("${pkgname}_${pkgver}.orig.tar.gz::https://github.com/cartesi/machine-emulator/archive/refs/tags/v${_pkgver}.tar.gz"
         "debian/patches/add-generated-files.diff::https://github.com/cartesi/machine-emulator/releases/download/v${_pkgver}/add-generated-files.diff")
sha256sums=("1a33fb7e0dd7030656ddbb214dcd2f5a569f64e906edb20f149b66b34e1e0dd3  ${pkgname}_${pkgver}.orig.tar.gz"
            "a892e2d9f5c331f5e80bcb5db4133e7db625aa4d14ffdf9467b75c4c34d1744f  debian/patches/add-generated-files.diff")
arch=any

prepare() {
    tar -xf ${pkgname}_${pkgver}.orig.tar.gz
    mv machine-emulator-${_pkgver} ${pkgname}-${pkgver}
    patch -d ${pkgname}-${pkgver} -Np1 < debian/patches/add-generated-files.diff
}
