#!/bin/bash
pkgname=cartesi-machine-guest-tools
pkgver=0.18.0
_pkgver=$pkgver
pkgrel=1
sources=("${pkgname}_${pkgver}.orig.tar.gz::https://github.com/cartesi/machine-guest-tools/archive/refs/tags/v$_pkgver.tar.gz")
sha256sums=("a16ee31a7abb0522ae70497721bf4856665297e1dd26d875a43fadbe48814bb6  ${pkgname}_${pkgver}.orig.tar.gz")
arch=riscv64

prepare() {
    # Extract
    tar -xf ${pkgname}_${pkgver}.orig.tar.gz
    mv machine-guest-tools-${_pkgver} ${pkgname}-${pkgver}
}
