#!/bin/bash
pkgname=cartesi-machine-guest-tools
pkgver=0.17.2
_pkgver=$pkgver
pkgrel=1
sources=("${pkgname}_${pkgver}.orig.tar.gz::https://github.com/cartesi/machine-guest-tools/archive/refs/tags/v$_pkgver.tar.gz")
sha256sums=("d95f501997d72ee85dfd3e1c51e4423cf3a1e6dede68b85aa44f8e2a225202cd  ${pkgname}_${pkgver}.orig.tar.gz")
arch=riscv64

prepare() {
    # Extract
    tar -xf ${pkgname}_${pkgver}.orig.tar.gz
    mv machine-guest-tools-${_pkgver} ${pkgname}-${pkgver}
}
