#!/bin/bash
pkgname=cartesi-rollups-node
pkgver=2.0.0-alpha.12
pkgrel=1
_commit=9fe9ce30ddbc95c22b4e92d1d2e89abeb6f76675
sources=("${pkgname}_${pkgver}.orig.tar.gz::https://github.com/cartesi/rollups-node/archive/${_commit}.tar.gz")
sha256sums=("74f12214685ade2b2430da189e4decbbb2b6eedc2141e721dcf56ee657ad6630  ${pkgname}_${pkgver}.orig.tar.gz")
arch=any

prepare() {
    tar -xf ${pkgname}_${pkgver}.orig.tar.gz
    mv rollups-node-${_commit} ${pkgname}-${pkgver}
}
