#!/bin/bash
pkgname=cartesi-machine-guest-linux-headers
pkgver=0.21.0
pkgrel=1
_linuxver=6.5.13-ctsi-2
sources=("${pkgname}_${pkgver}.orig.tar.xz::https://github.com/cartesi/machine-linux-image/releases/download/v$pkgver/linux-headers-$_linuxver-v$pkgver.tar.xz")
sha256sums="e3f140a8632fcfb18218e7aea32a7d002124d3dce5ba8121ae061ab7f40a6cf4  ${pkgname}_${pkgver}.orig.tar.xz"
arch=all

prepare() {
    # Extract
    tar -xf ${pkgname}_${pkgver}.orig.tar.xz
    mv include ${pkgname}-${pkgver}
}
